{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "5.3.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-5.3.29.jar",
          "url": "spring-jdbc-5.3.29.jar",
          "size": 428688,
          "sha512": "06f39e08eaa311572271145212bc87ab669aee57ff6693f95ee5d0ca6b3dea1ec04cccc4ccd4c28bc1432ae5968f543494fd5fba08e46621a1f247e28981bad7",
          "sha256": "e6c02a6dae2a2f75f14afdc2f3a759cb10feec10f1e8980832fcc3e068468af5",
          "sha1": "25c0b36f780af98b2d3b554e9a6258ac599b6115",
          "md5": "6d9e262c44186ff8f3619d80546d4a7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-5.3.29.jar",
          "url": "spring-jdbc-5.3.29.jar",
          "size": 428688,
          "sha512": "06f39e08eaa311572271145212bc87ab669aee57ff6693f95ee5d0ca6b3dea1ec04cccc4ccd4c28bc1432ae5968f543494fd5fba08e46621a1f247e28981bad7",
          "sha256": "e6c02a6dae2a2f75f14afdc2f3a759cb10feec10f1e8980832fcc3e068468af5",
          "sha1": "25c0b36f780af98b2d3b554e9a6258ac599b6115",
          "md5": "6d9e262c44186ff8f3619d80546d4a7a"
        }
      ]
    }
  ]
}
