{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.0.15.RELEASE"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15-javadoc.jar",
          "url": "spring-boot-gradle-plugin-2.7.15-javadoc.jar",
          "size": 242643,
          "sha512": "0b305e493fe74642b1a46d33fcba92f69419f7fe6934bfe44f07636063f00d329478ec5195ec82c546b5f7e6efb080433cd326349df4c675ed199619e0240c47",
          "sha256": "10bfe39bc114f4487c03920b5fc2690f738d3f0a4096d6d7caad663f21730f69",
          "sha1": "a99851129e77158833bed119e56a337dda64ae88",
          "md5": "c772f12b6d2c3c398b2ab30eecd08a26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15-sources.jar",
          "url": "spring-boot-gradle-plugin-2.7.15-sources.jar",
          "size": 73662,
          "sha512": "d0fd5013739c9a11ed81457e5d439755d34579536888e6ec33c7a76a1bf68cac00dc859676db3eb6a270c8239aa52edca8ced41487e5883af453a03b599ac98c",
          "sha256": "761bb7559464817b9b7d40ad07fe344b3b3a88ee88794113ef2a0dd445ebc117",
          "sha1": "0eab9d597c0eb583170fbcbb92bc3439be4ce056",
          "md5": "3a22d12d686436a688a7badbd7028f93"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        },
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        },
        {
          "name": "spring-boot-gradle-plugin-2.7.15.jar",
          "url": "spring-boot-gradle-plugin-2.7.15.jar",
          "size": 126622,
          "sha512": "c3e5206921ccb905c133998db3203c02cc835275936ea7b39e18e88f4276848cee9f123122bf7fc86ef1f9559302b3e4c6419164cfe4d097032d44c3aec185e1",
          "sha256": "b453f55087584ff129feb9c866b03ab684d2cc0f96b7246873c555a800fcdd89",
          "sha1": "30813b82c901375cfa66a3afd51d402086c530fb",
          "md5": "0a3aedcabb944e689087ab0e9552c157"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "2.7.15"
        }
      ]
    }
  ]
}
