{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.79"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.5.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15.jar",
          "url": "spring-boot-starter-validation-2.7.15.jar",
          "size": 4770,
          "sha512": "6bf3d31425ff23a6d7c2dc78e104a7e53b4c6239a3cb533944e8a7453ae1f21eabb879d575441498845310274a1ae5c1cfcb8e1f265d8fef04068204591f3f0d",
          "sha256": "39bba212a1b04b1b273f0ef8410ed9b926c7fa307331ac7e8f8a494ce3648662",
          "sha1": "25c3bc2528251de72e1291cdbc5de04a8d0c3b8e",
          "md5": "44678af1cc8b5e8fd222712cad91730b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.79"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.5.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15.jar",
          "url": "spring-boot-starter-validation-2.7.15.jar",
          "size": 4770,
          "sha512": "6bf3d31425ff23a6d7c2dc78e104a7e53b4c6239a3cb533944e8a7453ae1f21eabb879d575441498845310274a1ae5c1cfcb8e1f265d8fef04068204591f3f0d",
          "sha256": "39bba212a1b04b1b273f0ef8410ed9b926c7fa307331ac7e8f8a494ce3648662",
          "sha1": "25c3bc2528251de72e1291cdbc5de04a8d0c3b8e",
          "md5": "44678af1cc8b5e8fd222712cad91730b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15.jar",
          "url": "spring-boot-starter-validation-2.7.15.jar",
          "size": 4770,
          "sha512": "6bf3d31425ff23a6d7c2dc78e104a7e53b4c6239a3cb533944e8a7453ae1f21eabb879d575441498845310274a1ae5c1cfcb8e1f265d8fef04068204591f3f0d",
          "sha256": "39bba212a1b04b1b273f0ef8410ed9b926c7fa307331ac7e8f8a494ce3648662",
          "sha1": "25c3bc2528251de72e1291cdbc5de04a8d0c3b8e",
          "md5": "44678af1cc8b5e8fd222712cad91730b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15.jar",
          "url": "spring-boot-starter-validation-2.7.15.jar",
          "size": 4770,
          "sha512": "6bf3d31425ff23a6d7c2dc78e104a7e53b4c6239a3cb533944e8a7453ae1f21eabb879d575441498845310274a1ae5c1cfcb8e1f265d8fef04068204591f3f0d",
          "sha256": "39bba212a1b04b1b273f0ef8410ed9b926c7fa307331ac7e8f8a494ce3648662",
          "sha1": "25c3bc2528251de72e1291cdbc5de04a8d0c3b8e",
          "md5": "44678af1cc8b5e8fd222712cad91730b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-validation-2.7.15-javadoc.jar",
          "size": 4749,
          "sha512": "745bb19ca002fd88a64eea2e5c821ad3e1f67d0b3600cb3a8ce372b775caaccf954d41295c767004496cb94bb946cec2788d5225009938b709816668e88ab94c",
          "sha256": "691193f1933234641788cd16793d117b0ab51c437106f91af8100a2a8e60dfdb",
          "sha1": "6c9d7201747d177dcd6db8c6e9652fed02df947c",
          "md5": "6fd333a5b299cdc5887a8fe68febf14a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.7.15-sources.jar",
          "url": "spring-boot-starter-validation-2.7.15-sources.jar",
          "size": 4747,
          "sha512": "488dd1bca10e409fa188984f43bed2b162ad64cd63983c5c4a17823861f2061ee7633d8cb5f64ea1e3cd62abf66b8f167c565f945506456079661ee4e064a6ab",
          "sha256": "5a8e017af23b4dea46557cbf6a54f356977327c039d4226a1d45252b43a3cb90",
          "sha1": "cf43341b83c558e50f549b76d19b9233d8d22e64",
          "md5": "9dc3ee7d907ee1883e9f69814799176e"
        }
      ]
    }
  ]
}
