{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "5.3.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-5.3.29.jar",
          "url": "spring-aspects-5.3.29.jar",
          "size": 47238,
          "sha512": "9b6d590ad10e3c6f5a919aed7c614465d6155f2c8513b5e8f1dfb30d06c771403e2e44123ac1250a3ee26bf4829779f45fa510ba02d53e9993a2e3a8f24bca4a",
          "sha256": "51f76298e7e96986d92f77e59e7ea34ce2811b1e414ec1c0e486698c02278b5c",
          "sha1": "dbcf1c1ce847b0fb186b5dde18968c9a46900f28",
          "md5": "22a6604da04d25e12963e435e24fe610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-5.3.29.jar",
          "url": "spring-aspects-5.3.29.jar",
          "size": 47238,
          "sha512": "9b6d590ad10e3c6f5a919aed7c614465d6155f2c8513b5e8f1dfb30d06c771403e2e44123ac1250a3ee26bf4829779f45fa510ba02d53e9993a2e3a8f24bca4a",
          "sha256": "51f76298e7e96986d92f77e59e7ea34ce2811b1e414ec1c0e486698c02278b5c",
          "sha1": "dbcf1c1ce847b0fb186b5dde18968c9a46900f28",
          "md5": "22a6604da04d25e12963e435e24fe610"
        }
      ]
    }
  ]
}
