{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "5.3.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.29.jar",
          "url": "spring-context-5.3.29.jar",
          "size": 1275538,
          "sha512": "1bd6634c8d8a0bb7743018cc14582c1ac93fda5fdcafc7f84faa7e6d2e2edcf10e501dece506a2b691120ebd8fa012799584c3190735ed5bbd0f17fe4e812268",
          "sha256": "203a851cb017aff2cec77bd57dc46c9e6e250af4726bfa7a07f5d757179511b2",
          "sha1": "c374a72716d19220ca142efaab910adf5717c5d0",
          "md5": "43540ba9b705a1675d894bd915d0c9cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.29.jar",
          "url": "spring-context-5.3.29.jar",
          "size": 1275538,
          "sha512": "1bd6634c8d8a0bb7743018cc14582c1ac93fda5fdcafc7f84faa7e6d2e2edcf10e501dece506a2b691120ebd8fa012799584c3190735ed5bbd0f17fe4e812268",
          "sha256": "203a851cb017aff2cec77bd57dc46c9e6e250af4726bfa7a07f5d757179511b2",
          "sha1": "c374a72716d19220ca142efaab910adf5717c5d0",
          "md5": "43540ba9b705a1675d894bd915d0c9cd"
        }
      ]
    }
  ]
}
