{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15.jar",
          "url": "spring-boot-loader-tools-2.7.15.jar",
          "size": 250264,
          "sha512": "f753c34f8788078784aeee707bee481e6027cf7dce619ad2e291e9f6c42b65bd82eefbb3113a99c7e9e5b5f2479da90b834a915c7b7497f2df2cdf704a038ff4",
          "sha256": "91abbbd9d6d5dc297fbabaf536885f5d7eaf2a0d35ac7c2495d4f4c1273361ac",
          "sha1": "9c8073c2625254bc7aa20fb26f341021a287a1b7",
          "md5": "b07c16f3b3edc3266aef47ddab21aaf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15.jar",
          "url": "spring-boot-loader-tools-2.7.15.jar",
          "size": 250264,
          "sha512": "f753c34f8788078784aeee707bee481e6027cf7dce619ad2e291e9f6c42b65bd82eefbb3113a99c7e9e5b5f2479da90b834a915c7b7497f2df2cdf704a038ff4",
          "sha256": "91abbbd9d6d5dc297fbabaf536885f5d7eaf2a0d35ac7c2495d4f4c1273361ac",
          "sha1": "9c8073c2625254bc7aa20fb26f341021a287a1b7",
          "md5": "b07c16f3b3edc3266aef47ddab21aaf8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15-javadoc.jar",
          "url": "spring-boot-loader-tools-2.7.15-javadoc.jar",
          "size": 167071,
          "sha512": "9acdf3a731e0b00054a5999930370b2a4732b7a014416df73b8f261470b6016e427ee6be609677b772ee91819aeddb9b40d6df3b0fb00f63bc7b9f874c7c6200",
          "sha256": "bceaa9c080dc8ac6a72b81a833a279b6bf1e905930839ceb7d141f3e58144a8c",
          "sha1": "818f2725c68250ff59aa43a911049686a97682ac",
          "md5": "65ed836c04087f63622786eb05fd841d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15-sources.jar",
          "url": "spring-boot-loader-tools-2.7.15-sources.jar",
          "size": 70834,
          "sha512": "d266e21d890975fb569ad9ef72669902b8b103a928fe3e1675a46f5c4081fe4209985f563970b869c49f6d9cd0e81f3d9e26a52d9e4e43d23d0a0661f20afba0",
          "sha256": "945c950f443fdd12a45460f3c0455a4f424daedf5583e7f29a1dffce86610ca6",
          "sha1": "af095be04a7ee4c914800f225c01515430ad3896",
          "md5": "470eb7b4f3dc5612d4e8975d7e841a0a"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15.jar",
          "url": "spring-boot-loader-tools-2.7.15.jar",
          "size": 250264,
          "sha512": "f753c34f8788078784aeee707bee481e6027cf7dce619ad2e291e9f6c42b65bd82eefbb3113a99c7e9e5b5f2479da90b834a915c7b7497f2df2cdf704a038ff4",
          "sha256": "91abbbd9d6d5dc297fbabaf536885f5d7eaf2a0d35ac7c2495d4f4c1273361ac",
          "sha1": "9c8073c2625254bc7aa20fb26f341021a287a1b7",
          "md5": "b07c16f3b3edc3266aef47ddab21aaf8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.7.15.jar",
          "url": "spring-boot-loader-tools-2.7.15.jar",
          "size": 250264,
          "sha512": "f753c34f8788078784aeee707bee481e6027cf7dce619ad2e291e9f6c42b65bd82eefbb3113a99c7e9e5b5f2479da90b834a915c7b7497f2df2cdf704a038ff4",
          "sha256": "91abbbd9d6d5dc297fbabaf536885f5d7eaf2a0d35ac7c2495d4f4c1273361ac",
          "sha1": "9c8073c2625254bc7aa20fb26f341021a287a1b7",
          "md5": "b07c16f3b3edc3266aef47ddab21aaf8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "2.7.15"
        }
      ]
    }
  ]
}
