spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:querydsl_board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        show_sql: true # console

logging:
  level:
    org.hibernate.sql: debug # logger
    org.hibernate.type: trace%