{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15.jar",
          "size": 213848,
          "sha512": "841d97b0a3e658c0f8373962cc2c052269c8cd05a6d4005e4c0ebf9e5df9888ece915025e788b6b268d2b45d4a30f5948cdc0f563dc619206b923a88fd34181e",
          "sha256": "a9794cfc11fed66d7807209bd0a1b61bf7f0414eb9f394ab327ae4cac405384b",
          "sha1": "f59ccd8f7db4c88bee112e59875a40767456664e",
          "md5": "53ac17878958f5bcc1a8128c8a3d16d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15.jar",
          "size": 213848,
          "sha512": "841d97b0a3e658c0f8373962cc2c052269c8cd05a6d4005e4c0ebf9e5df9888ece915025e788b6b268d2b45d4a30f5948cdc0f563dc619206b923a88fd34181e",
          "sha256": "a9794cfc11fed66d7807209bd0a1b61bf7f0414eb9f394ab327ae4cac405384b",
          "sha1": "f59ccd8f7db4c88bee112e59875a40767456664e",
          "md5": "53ac17878958f5bcc1a8128c8a3d16d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15-javadoc.jar",
          "size": 416890,
          "sha512": "346f719460c3032ea9292864150d52f15cca991259c2fa680bd9b9204a23092f51f9981cb255b3858858743d8df451684d5fa50a0d40f3d050e210d9c328b143",
          "sha256": "18cf5773eff8fcaaad62edbdc5ba01450a6cb0d6629b73f775456dc4fee1fc40",
          "sha1": "1aed86b70a617625631e9564fe1713155e541648",
          "md5": "bfd15ea6df8c8b73596e6a6b1d42756d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15-sources.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15-sources.jar",
          "size": 218284,
          "sha512": "cdd25adad3f98238dbcdd446af703140723cad7ca2b8f8c860079661b6d6bb4eada5a0c6f689d9bbf2e4dcf56af8ac7aba3b6c33a4b4ca88071238975ac23bdd",
          "sha256": "ab5a39d25dff0d214e4ddf031944de32bc8f5b454b49af160beba93c6d323a5a",
          "sha1": "b76af498a0b6d9ac235af8b088e8aea22fc4d7e9",
          "md5": "42d7e789e3f00df951830a4a9e01b0a8"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15.jar",
          "size": 213848,
          "sha512": "841d97b0a3e658c0f8373962cc2c052269c8cd05a6d4005e4c0ebf9e5df9888ece915025e788b6b268d2b45d4a30f5948cdc0f563dc619206b923a88fd34181e",
          "sha256": "a9794cfc11fed66d7807209bd0a1b61bf7f0414eb9f394ab327ae4cac405384b",
          "sha1": "f59ccd8f7db4c88bee112e59875a40767456664e",
          "md5": "53ac17878958f5bcc1a8128c8a3d16d9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.7.15.jar",
          "url": "spring-boot-test-autoconfigure-2.7.15.jar",
          "size": 213848,
          "sha512": "841d97b0a3e658c0f8373962cc2c052269c8cd05a6d4005e4c0ebf9e5df9888ece915025e788b6b268d2b45d4a30f5948cdc0f563dc619206b923a88fd34181e",
          "sha256": "a9794cfc11fed66d7807209bd0a1b61bf7f0414eb9f394ab327ae4cac405384b",
          "sha1": "f59ccd8f7db4c88bee112e59875a40767456664e",
          "md5": "53ac17878958f5bcc1a8128c8a3d16d9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.7.15"
        }
      ]
    }
  ]
}
