{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15.jar",
          "size": 4760,
          "sha512": "05b7369489844545acacb044835db8ccfcbc0d893417379d45467cadf32378af1daaac1cf2a2024fe0611dc019e426f5bbfc15661ad996c07f100bb2e305b0c5",
          "sha256": "3d7c3c5d831a7778c7da3eb2bd151b2fbd53dbcb51882bd89444e10d57167e64",
          "sha1": "93fe758d2f6fdda6ec5494a984c980164f529486",
          "md5": "a36734f44580b2e5a43cf6fd74a666b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15.jar",
          "size": 4760,
          "sha512": "05b7369489844545acacb044835db8ccfcbc0d893417379d45467cadf32378af1daaac1cf2a2024fe0611dc019e426f5bbfc15661ad996c07f100bb2e305b0c5",
          "sha256": "3d7c3c5d831a7778c7da3eb2bd151b2fbd53dbcb51882bd89444e10d57167e64",
          "sha1": "93fe758d2f6fdda6ec5494a984c980164f529486",
          "md5": "a36734f44580b2e5a43cf6fd74a666b4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15.jar",
          "size": 4760,
          "sha512": "05b7369489844545acacb044835db8ccfcbc0d893417379d45467cadf32378af1daaac1cf2a2024fe0611dc019e426f5bbfc15661ad996c07f100bb2e305b0c5",
          "sha256": "3d7c3c5d831a7778c7da3eb2bd151b2fbd53dbcb51882bd89444e10d57167e64",
          "sha1": "93fe758d2f6fdda6ec5494a984c980164f529486",
          "md5": "a36734f44580b2e5a43cf6fd74a666b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15.jar",
          "size": 4760,
          "sha512": "05b7369489844545acacb044835db8ccfcbc0d893417379d45467cadf32378af1daaac1cf2a2024fe0611dc019e426f5bbfc15661ad996c07f100bb2e305b0c5",
          "sha256": "3d7c3c5d831a7778c7da3eb2bd151b2fbd53dbcb51882bd89444e10d57167e64",
          "sha1": "93fe758d2f6fdda6ec5494a984c980164f529486",
          "md5": "a36734f44580b2e5a43cf6fd74a666b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15-javadoc.jar",
          "size": 4751,
          "sha512": "d0faad782ae6328c91736ae152b4457671d6fac895b8bc52193b20726c61ccde14e1dd2f1bd52e5f0131548cccb7933cfc288e1055b83d777cc2ea9edbb203cf",
          "sha256": "fdafd6492ce5d7eeba5620366828ce15f6f54dbece300b14dba99596455178c4",
          "sha1": "d5e01cc54b11c29f21afd3046a68a47b65d7395c",
          "md5": "52e2db675e6cf57cab00bf57ec7df5ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.15-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.15-sources.jar",
          "size": 4749,
          "sha512": "3417e746d667016d9200ad2dcf6699b96b8d93ce1670fa67087d236b8ecc96368323abae631a2bf4a367611a0d18fae2d74ea30f96d9a33d9bd245d0b5a6fa0a",
          "sha256": "cce10970c87633b8082b49f39cbe2fc76adb9bdbc32b79799c5d3ec4f0f49537",
          "sha1": "b81cd70073c26ea28e12dc66cd1809774a900413",
          "md5": "3d924560d830732929388a36360aef13"
        }
      ]
    }
  ]
}
