{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.29.jar",
          "url": "spring-web-5.3.29.jar",
          "size": 1642650,
          "sha512": "965b1f2e123cf7b1dc86a297069861691e29cb947b0218b05e7ec6184de587ba63214d46d0d1f2fed1df37b124b517dae77331db1ae9d4b0fa5e7f640af44fd2",
          "sha256": "540fc44b0ecc62c0225c49779730d7f52c8be56a609c9dd70ec6d1b34cbd1f56",
          "sha1": "4cd333e48d9a05d05c05ae7426242ecfe4cfb681",
          "md5": "627acac21bedc33a305e8eac310887e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.29.jar",
          "url": "spring-web-5.3.29.jar",
          "size": 1642650,
          "sha512": "965b1f2e123cf7b1dc86a297069861691e29cb947b0218b05e7ec6184de587ba63214d46d0d1f2fed1df37b124b517dae77331db1ae9d4b0fa5e7f640af44fd2",
          "sha256": "540fc44b0ecc62c0225c49779730d7f52c8be56a609c9dd70ec6d1b34cbd1f56",
          "sha1": "4cd333e48d9a05d05c05ae7426242ecfe4cfb681",
          "md5": "627acac21bedc33a305e8eac310887e6"
        }
      ]
    }
  ]
}
