{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15.jar",
          "url": "spring-boot-starter-test-2.7.15.jar",
          "size": 4794,
          "sha512": "0685c577d95402121b4149aed3d1c84a8801a8d4795a30479c5eb0f43a97e4cb437bd475bb47d1843481a54d12f0441a2e35f1b4410685f64c5ba64009c3c56b",
          "sha256": "809f09f979cb0b5b68a6e23daf8ffd8dcffc383e7f8b014f95b18fe485f9e32f",
          "sha1": "b9bf93cbd1c5d5d09dd798fca143e55cb0662777",
          "md5": "aec39ac2690074ccfe2451eee17ff1bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15.jar",
          "url": "spring-boot-starter-test-2.7.15.jar",
          "size": 4794,
          "sha512": "0685c577d95402121b4149aed3d1c84a8801a8d4795a30479c5eb0f43a97e4cb437bd475bb47d1843481a54d12f0441a2e35f1b4410685f64c5ba64009c3c56b",
          "sha256": "809f09f979cb0b5b68a6e23daf8ffd8dcffc383e7f8b014f95b18fe485f9e32f",
          "sha1": "b9bf93cbd1c5d5d09dd798fca143e55cb0662777",
          "md5": "aec39ac2690074ccfe2451eee17ff1bf"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15.jar",
          "url": "spring-boot-starter-test-2.7.15.jar",
          "size": 4794,
          "sha512": "0685c577d95402121b4149aed3d1c84a8801a8d4795a30479c5eb0f43a97e4cb437bd475bb47d1843481a54d12f0441a2e35f1b4410685f64c5ba64009c3c56b",
          "sha256": "809f09f979cb0b5b68a6e23daf8ffd8dcffc383e7f8b014f95b18fe485f9e32f",
          "sha1": "b9bf93cbd1c5d5d09dd798fca143e55cb0662777",
          "md5": "aec39ac2690074ccfe2451eee17ff1bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15.jar",
          "url": "spring-boot-starter-test-2.7.15.jar",
          "size": 4794,
          "sha512": "0685c577d95402121b4149aed3d1c84a8801a8d4795a30479c5eb0f43a97e4cb437bd475bb47d1843481a54d12f0441a2e35f1b4410685f64c5ba64009c3c56b",
          "sha256": "809f09f979cb0b5b68a6e23daf8ffd8dcffc383e7f8b014f95b18fe485f9e32f",
          "sha1": "b9bf93cbd1c5d5d09dd798fca143e55cb0662777",
          "md5": "aec39ac2690074ccfe2451eee17ff1bf"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-test-2.7.15-javadoc.jar",
          "size": 4745,
          "sha512": "36ba12d38549b6b4c5b03347469f056e8193e984273b22acbecf02c5a7f45ed00c49323dc913560e99c0de7c1d75f7ef4e46fe087f14c7b4b05f1e36b5e8740a",
          "sha256": "d86df92f08889e50562eea5745215038faff7d937fd82ab20578cc3a12d54121",
          "sha1": "0abe2e10c57b896ff94272ab1d754384f377d525",
          "md5": "5fe0935b9bb36b6538f5ddcbef9fc747"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.15-sources.jar",
          "url": "spring-boot-starter-test-2.7.15-sources.jar",
          "size": 4743,
          "sha512": "7c58b9937d6844c00a0311a1982ce978b754399ceedd0686230343c03fa4b0ed17c163fa00ca6c7c8190e7f80ba2ab5f72d1ebc8324169b328e07312fbfb3f55",
          "sha256": "e13a507f2498103b7bbff89aa723012a7d72d3eaa46406da5ff51b1e6b405b7f",
          "sha1": "b2dfa3537b6c5c9c47b5d39a7da51ed412ee6d81",
          "md5": "b3203767e5a0962f2f4a1c5ca3f5a046"
        }
      ]
    }
  ]
}
