{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15.jar",
          "url": "spring-boot-starter-aop-2.7.15.jar",
          "size": 4774,
          "sha512": "81e8aa8d3f221db02bf8c089b4c4c038212e1d75e8e4b7163af65e13622add17f49b4c1067b9bd6d82aadc2781cca663249d7d7e35c6640dfeeeabe2fbad0abe",
          "sha256": "887e8176f917223a48269e2d45db80cb6ba53273d062b0a4b4ca8bb2e51ff855",
          "sha1": "190b2d96cec2be49e686089d349dbc1f0d382b5a",
          "md5": "c206ba8293433a3ec7072be72dc3e536"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15.jar",
          "url": "spring-boot-starter-aop-2.7.15.jar",
          "size": 4774,
          "sha512": "81e8aa8d3f221db02bf8c089b4c4c038212e1d75e8e4b7163af65e13622add17f49b4c1067b9bd6d82aadc2781cca663249d7d7e35c6640dfeeeabe2fbad0abe",
          "sha256": "887e8176f917223a48269e2d45db80cb6ba53273d062b0a4b4ca8bb2e51ff855",
          "sha1": "190b2d96cec2be49e686089d349dbc1f0d382b5a",
          "md5": "c206ba8293433a3ec7072be72dc3e536"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15.jar",
          "url": "spring-boot-starter-aop-2.7.15.jar",
          "size": 4774,
          "sha512": "81e8aa8d3f221db02bf8c089b4c4c038212e1d75e8e4b7163af65e13622add17f49b4c1067b9bd6d82aadc2781cca663249d7d7e35c6640dfeeeabe2fbad0abe",
          "sha256": "887e8176f917223a48269e2d45db80cb6ba53273d062b0a4b4ca8bb2e51ff855",
          "sha1": "190b2d96cec2be49e686089d349dbc1f0d382b5a",
          "md5": "c206ba8293433a3ec7072be72dc3e536"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15.jar",
          "url": "spring-boot-starter-aop-2.7.15.jar",
          "size": 4774,
          "sha512": "81e8aa8d3f221db02bf8c089b4c4c038212e1d75e8e4b7163af65e13622add17f49b4c1067b9bd6d82aadc2781cca663249d7d7e35c6640dfeeeabe2fbad0abe",
          "sha256": "887e8176f917223a48269e2d45db80cb6ba53273d062b0a4b4ca8bb2e51ff855",
          "sha1": "190b2d96cec2be49e686089d349dbc1f0d382b5a",
          "md5": "c206ba8293433a3ec7072be72dc3e536"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-aop-2.7.15-javadoc.jar",
          "size": 4746,
          "sha512": "564adfb8c44a66ec8dac71b9c7f11e81f049d483ddabad81ec2e9ee31cc4943a2bb6f6f71dab13c2f262ac7308624a4d42918c2c6d11aaf7320a26211eb26fee",
          "sha256": "c32984e612c993c0f1255ab109572bb229960366e6d307daf206a7cf2a3f6541",
          "sha1": "c72804a5e89b1a2a03de0e97eef494b36917c111",
          "md5": "eb224fd1b399608a99467aac645d27d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-2.7.15-sources.jar",
          "url": "spring-boot-starter-aop-2.7.15-sources.jar",
          "size": 4744,
          "sha512": "7fccfa2549074e7f19ed302cc384b16301831a0f2ff0dd71f863e0a2319716ce49423d97c2e2f55dfada5cca21c54ba2b4909b8251ddc3dc6cdee4b94d6f8dad",
          "sha256": "286a8748e76a0a0573174cab3737077d704c226071bd0df2ac96d02d707c8418",
          "sha1": "64f9fbbc65bf38231b28683b225f65a9d7e10c15",
          "md5": "985669b53d3233b2900b920b1143969d"
        }
      ]
    }
  ]
}
