{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15.jar",
          "url": "spring-boot-buildpack-platform-2.7.15.jar",
          "size": 258714,
          "sha512": "a36f85d585f040631073f223fb55b291f8b92afa8670cd7183af0aa6b9c2cd68f0f96f5b7c57e3967b0964d7a532dd2e20e5783b71d1c2ee6d0b24c41f1eebba",
          "sha256": "907802c1973f0cf7fed28d1d1de92f7731c49d331c61561b034ef84931f48a63",
          "sha1": "9765d3a3e772705ef85d4f165b339212a18de202",
          "md5": "4b5300ff95887516acc97ee922f02e42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15.jar",
          "url": "spring-boot-buildpack-platform-2.7.15.jar",
          "size": 258714,
          "sha512": "a36f85d585f040631073f223fb55b291f8b92afa8670cd7183af0aa6b9c2cd68f0f96f5b7c57e3967b0964d7a532dd2e20e5783b71d1c2ee6d0b24c41f1eebba",
          "sha256": "907802c1973f0cf7fed28d1d1de92f7731c49d331c61561b034ef84931f48a63",
          "sha1": "9765d3a3e772705ef85d4f165b339212a18de202",
          "md5": "4b5300ff95887516acc97ee922f02e42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15-javadoc.jar",
          "url": "spring-boot-buildpack-platform-2.7.15-javadoc.jar",
          "size": 309381,
          "sha512": "8986ec408b55799c90727302b46d5bc1dbc61beeced14b581ef0ed8eff8fd07c9321fdfb83dfd9c09a44fc2ca217c81dedbd71fe6790b504669d62b7178917af",
          "sha256": "bd923f6fe21287a1fd70b3d599d7b28547da47b83b03a402aa76a2c1dd09c7ec",
          "sha1": "487eb78c88f6646d50ad37f262116ba54607c7be",
          "md5": "56ab2c7c017507d15427b083909a97cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15-sources.jar",
          "url": "spring-boot-buildpack-platform-2.7.15-sources.jar",
          "size": 164214,
          "sha512": "45ab7d68f9aa067277a591e505f8d6717693f4b1d8ce1e836709d4ecf35341508d07f24bf5e333571e227b744c5d76ef4394502520590c1c2974e1156dcfd547",
          "sha256": "2c9cf0728634007f942675d47a5b11ecc207a1c8db49fdd1f2c4c2731dc5f716",
          "sha1": "673a76b5bae528401c3da878053564aaaaf7af9e",
          "md5": "52211cb764ae338dadff06d1acf92c2f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15.jar",
          "url": "spring-boot-buildpack-platform-2.7.15.jar",
          "size": 258714,
          "sha512": "a36f85d585f040631073f223fb55b291f8b92afa8670cd7183af0aa6b9c2cd68f0f96f5b7c57e3967b0964d7a532dd2e20e5783b71d1c2ee6d0b24c41f1eebba",
          "sha256": "907802c1973f0cf7fed28d1d1de92f7731c49d331c61561b034ef84931f48a63",
          "sha1": "9765d3a3e772705ef85d4f165b339212a18de202",
          "md5": "4b5300ff95887516acc97ee922f02e42"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.15.jar",
          "url": "spring-boot-buildpack-platform-2.7.15.jar",
          "size": 258714,
          "sha512": "a36f85d585f040631073f223fb55b291f8b92afa8670cd7183af0aa6b9c2cd68f0f96f5b7c57e3967b0964d7a532dd2e20e5783b71d1c2ee6d0b24c41f1eebba",
          "sha256": "907802c1973f0cf7fed28d1d1de92f7731c49d331c61561b034ef84931f48a63",
          "sha1": "9765d3a3e772705ef85d4f165b339212a18de202",
          "md5": "4b5300ff95887516acc97ee922f02e42"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.7.15"
        }
      ]
    }
  ]
}
