{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.15.jar",
          "url": "spring-boot-starter-2.7.15.jar",
          "size": 4772,
          "sha512": "d53a42cd326b534b61f1a75e8f7cc95183d7daf0ed4c8e59f8642046a04c23b7c80731b710dbdecabce5b0c867d83b77b4522072717533843b8599b6b1f2bcae",
          "sha256": "787868606b4163e66c6e2ad7afa8c178ec5a82650f9726fcb8f4553ff51778d2",
          "sha1": "6ea75176edb5ba47addd6143b3e0fec25811be1d",
          "md5": "feb06d4b7f2c1af83d11bab8c447882f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.15.jar",
          "url": "spring-boot-starter-2.7.15.jar",
          "size": 4772,
          "sha512": "d53a42cd326b534b61f1a75e8f7cc95183d7daf0ed4c8e59f8642046a04c23b7c80731b710dbdecabce5b0c867d83b77b4522072717533843b8599b6b1f2bcae",
          "sha256": "787868606b4163e66c6e2ad7afa8c178ec5a82650f9726fcb8f4553ff51778d2",
          "sha1": "6ea75176edb5ba47addd6143b3e0fec25811be1d",
          "md5": "feb06d4b7f2c1af83d11bab8c447882f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.15.jar",
          "url": "spring-boot-starter-2.7.15.jar",
          "size": 4772,
          "sha512": "d53a42cd326b534b61f1a75e8f7cc95183d7daf0ed4c8e59f8642046a04c23b7c80731b710dbdecabce5b0c867d83b77b4522072717533843b8599b6b1f2bcae",
          "sha256": "787868606b4163e66c6e2ad7afa8c178ec5a82650f9726fcb8f4553ff51778d2",
          "sha1": "6ea75176edb5ba47addd6143b3e0fec25811be1d",
          "md5": "feb06d4b7f2c1af83d11bab8c447882f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.15.jar",
          "url": "spring-boot-starter-2.7.15.jar",
          "size": 4772,
          "sha512": "d53a42cd326b534b61f1a75e8f7cc95183d7daf0ed4c8e59f8642046a04c23b7c80731b710dbdecabce5b0c867d83b77b4522072717533843b8599b6b1f2bcae",
          "sha256": "787868606b4163e66c6e2ad7afa8c178ec5a82650f9726fcb8f4553ff51778d2",
          "sha1": "6ea75176edb5ba47addd6143b3e0fec25811be1d",
          "md5": "feb06d4b7f2c1af83d11bab8c447882f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-2.7.15-javadoc.jar",
          "size": 4740,
          "sha512": "ac62068306930a52ff280eaae87d0360393b2affde49a489ef2997345cec82b5f5004656e03f69e3d209e314249776dce0684b97fcf08b28782b1e359e2e6803",
          "sha256": "a827425a9c30d6a8aa073e33fe3b6109de069dd2503f8f7a51af805e1b3183b1",
          "sha1": "78e8e2045ec04127543b2fedc54dd4cc213133fb",
          "md5": "4d2619f2e331034534939782825ee504"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.15-sources.jar",
          "url": "spring-boot-starter-2.7.15-sources.jar",
          "size": 4738,
          "sha512": "15f186c35d54d37293895e563684df9725419175949169aac55b029ba7ced77c198f7de5afbf6546aee79d065621fb09860a14c3509b3088b862a482619dcd5d",
          "sha256": "2190e02d33151507b329c27c60c8521f8513560e660dfbfc729b9c576d7524f4",
          "sha1": "0971d20405cecfed0f7629618401636b455ee1d2",
          "md5": "9e3e3339102decc38dfe11e242c5591e"
        }
      ]
    }
  ]
}
