{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15.jar",
          "url": "spring-boot-starter-web-2.7.15.jar",
          "size": 4807,
          "sha512": "b8f02ac37a7585b0987cd169a660f8010b1b3a728703282f97912726815d25f9127f97c8ea6f1d5e3e4dc4d103c6889d01ed71b64ec59a7e2640ff90aa7b8df7",
          "sha256": "cb46e76202647fd769f8c21a1eeac6bff7c10bf1db6fa12ff50f267cb325689d",
          "sha1": "80f227f160fd83e4d3e1fb10ec59530e4faae1e0",
          "md5": "edb65eca46d9708b6c9a4ff9f63b0288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15.jar",
          "url": "spring-boot-starter-web-2.7.15.jar",
          "size": 4807,
          "sha512": "b8f02ac37a7585b0987cd169a660f8010b1b3a728703282f97912726815d25f9127f97c8ea6f1d5e3e4dc4d103c6889d01ed71b64ec59a7e2640ff90aa7b8df7",
          "sha256": "cb46e76202647fd769f8c21a1eeac6bff7c10bf1db6fa12ff50f267cb325689d",
          "sha1": "80f227f160fd83e4d3e1fb10ec59530e4faae1e0",
          "md5": "edb65eca46d9708b6c9a4ff9f63b0288"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15.jar",
          "url": "spring-boot-starter-web-2.7.15.jar",
          "size": 4807,
          "sha512": "b8f02ac37a7585b0987cd169a660f8010b1b3a728703282f97912726815d25f9127f97c8ea6f1d5e3e4dc4d103c6889d01ed71b64ec59a7e2640ff90aa7b8df7",
          "sha256": "cb46e76202647fd769f8c21a1eeac6bff7c10bf1db6fa12ff50f267cb325689d",
          "sha1": "80f227f160fd83e4d3e1fb10ec59530e4faae1e0",
          "md5": "edb65eca46d9708b6c9a4ff9f63b0288"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15.jar",
          "url": "spring-boot-starter-web-2.7.15.jar",
          "size": 4807,
          "sha512": "b8f02ac37a7585b0987cd169a660f8010b1b3a728703282f97912726815d25f9127f97c8ea6f1d5e3e4dc4d103c6889d01ed71b64ec59a7e2640ff90aa7b8df7",
          "sha256": "cb46e76202647fd769f8c21a1eeac6bff7c10bf1db6fa12ff50f267cb325689d",
          "sha1": "80f227f160fd83e4d3e1fb10ec59530e4faae1e0",
          "md5": "edb65eca46d9708b6c9a4ff9f63b0288"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-web-2.7.15-javadoc.jar",
          "size": 4746,
          "sha512": "657e0c9e64c1442f82dcead57b94cfc146aae40e64af840ef9bfd731e60eb3a59c7a8676392ae55f61918fdd98b4d33777bd03102f80321649f2c4297a4a4598",
          "sha256": "974de3e1902ab00c6736a5b6dd2596035f33dda1ea2dd6788ca860f9f7ea577e",
          "sha1": "21b987e9ff4cb79d057cb1bba305b4c748f1df4a",
          "md5": "a7d16850a7a67b540f634a0ac28b8d94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.7.15-sources.jar",
          "url": "spring-boot-starter-web-2.7.15-sources.jar",
          "size": 4745,
          "sha512": "8961c7103a7e96b7adba106e93941e4785f7e07356242d830651833ad4c09e034a7ef7c95ef262c9b1c17bb1dfcb60cf3aa0e084a8e493d2301c6f2f3036729b",
          "sha256": "814ab46a81edda9afcbe0587e0a9b448599ae9ec21e45708473f6b2905797019",
          "sha1": "709a7a2346695d18e5a9d78ef56c2efd9b99157a",
          "md5": "d4741e729574186c0c2a6c045acf0aef"
        }
      ]
    }
  ]
}
