{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "5.3.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.29.jar",
          "url": "spring-webmvc-5.3.29.jar",
          "size": 1029881,
          "sha512": "0431056839bc2a39b8ac64e3b95940c93c8d6a3fc191d85e2aaebc818874df045e6d8f7b5a7ded39c1153f0f7d220f5e242785e3b1e4114613bc53dfbc78f144",
          "sha256": "ea8953e401d46d5b3d3ba5a98078b37274c91a87e04407f49b7e761a569d925a",
          "sha1": "fdaefee29fcb8459aab748b571d8bb7bb7fdb175",
          "md5": "1715b547dfa191896ff983f1f567eca8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.29.jar",
          "url": "spring-webmvc-5.3.29.jar",
          "size": 1029881,
          "sha512": "0431056839bc2a39b8ac64e3b95940c93c8d6a3fc191d85e2aaebc818874df045e6d8f7b5a7ded39c1153f0f7d220f5e242785e3b1e4114613bc53dfbc78f144",
          "sha256": "ea8953e401d46d5b3d3ba5a98078b37274c91a87e04407f49b7e761a569d925a",
          "sha1": "fdaefee29fcb8459aab748b571d8bb7bb7fdb175",
          "md5": "1715b547dfa191896ff983f1f567eca8"
        }
      ]
    }
  ]
}
