{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15.jar",
          "url": "spring-boot-autoconfigure-2.7.15.jar",
          "size": 1689246,
          "sha512": "56dcdefa42ff1d563ab6747f18a22675f29c034f4e48d12d9c24ddfefdc81b6b36568f27c21a59c44ed73dc74eef10671b9fb79f9458d3a571daf6bfe57f6762",
          "sha256": "871882650a4c09836d9ebff990419787334ee339c8c4c05f913b57aaabfef418",
          "sha1": "ca07c5ec0347342e207de3d26c0b686d43be60d5",
          "md5": "558a5e89c5c38479903f6e0a4158e7ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15.jar",
          "url": "spring-boot-autoconfigure-2.7.15.jar",
          "size": 1689246,
          "sha512": "56dcdefa42ff1d563ab6747f18a22675f29c034f4e48d12d9c24ddfefdc81b6b36568f27c21a59c44ed73dc74eef10671b9fb79f9458d3a571daf6bfe57f6762",
          "sha256": "871882650a4c09836d9ebff990419787334ee339c8c4c05f913b57aaabfef418",
          "sha1": "ca07c5ec0347342e207de3d26c0b686d43be60d5",
          "md5": "558a5e89c5c38479903f6e0a4158e7ee"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15.jar",
          "url": "spring-boot-autoconfigure-2.7.15.jar",
          "size": 1689246,
          "sha512": "56dcdefa42ff1d563ab6747f18a22675f29c034f4e48d12d9c24ddfefdc81b6b36568f27c21a59c44ed73dc74eef10671b9fb79f9458d3a571daf6bfe57f6762",
          "sha256": "871882650a4c09836d9ebff990419787334ee339c8c4c05f913b57aaabfef418",
          "sha1": "ca07c5ec0347342e207de3d26c0b686d43be60d5",
          "md5": "558a5e89c5c38479903f6e0a4158e7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15.jar",
          "url": "spring-boot-autoconfigure-2.7.15.jar",
          "size": 1689246,
          "sha512": "56dcdefa42ff1d563ab6747f18a22675f29c034f4e48d12d9c24ddfefdc81b6b36568f27c21a59c44ed73dc74eef10671b9fb79f9458d3a571daf6bfe57f6762",
          "sha256": "871882650a4c09836d9ebff990419787334ee339c8c4c05f913b57aaabfef418",
          "sha1": "ca07c5ec0347342e207de3d26c0b686d43be60d5",
          "md5": "558a5e89c5c38479903f6e0a4158e7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15-javadoc.jar",
          "url": "spring-boot-autoconfigure-2.7.15-javadoc.jar",
          "size": 2535100,
          "sha512": "beaa3d98fbd592b504b86afe2a5d94ac07822b5f6b91f2d6c1f15a40175b63bd1bbe3591f72156f528c2050c5438d8fd2f1ebb0ed292094226fa9cd2738b2dd5",
          "sha256": "6d3f8e7b56ecd9f7ee13153b58677a1a01c98d79f95f17da14f8baf8dccc6418",
          "sha1": "754dca30fe92b2591af9cb965a7656148b221eaa",
          "md5": "b680400bea92e6fa6b559a67c25aaf49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.7.15-sources.jar",
          "url": "spring-boot-autoconfigure-2.7.15-sources.jar",
          "size": 1006603,
          "sha512": "629d13ee3bd64da65c7a600ad3dd8b6405bdba6c50f34889abfd4c316dacdf9de8dad1cd1af9f2e0ebd8fbac1bce2c6134e10eb0c2dc256223cfa785755667ed",
          "sha256": "cf7b2af5d430d8d955b9a23421bb3b01b8118cb0027428b3c45aad5a15a3bb4c",
          "sha1": "1348b702112b318bf64583aa7ba63eee46182318",
          "md5": "0a128e4f91fefb9ba966a44e82760e44"
        }
      ]
    }
  ]
}
