{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.79"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.79"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.79"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15.jar",
          "url": "spring-boot-starter-tomcat-2.7.15.jar",
          "size": 4798,
          "sha512": "1af27c4e07b55254d5764743a61801cf12bc37c4a129a402998c88c1f51a44c2c154e2038411cd998ab42e286e89465fcd49261a7bdddd16ef757827b4785d77",
          "sha256": "51c096873d554a84c7bde8bd2dba385e6c0b6d58aaf8a41ee6b4ff65435c0c65",
          "sha1": "85a01164a2ceafb4ba1b9398bb99f4dd55e02499",
          "md5": "2bcb4827e1275152fda35b1224ef2955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.79"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.79"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.79"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15.jar",
          "url": "spring-boot-starter-tomcat-2.7.15.jar",
          "size": 4798,
          "sha512": "1af27c4e07b55254d5764743a61801cf12bc37c4a129a402998c88c1f51a44c2c154e2038411cd998ab42e286e89465fcd49261a7bdddd16ef757827b4785d77",
          "sha256": "51c096873d554a84c7bde8bd2dba385e6c0b6d58aaf8a41ee6b4ff65435c0c65",
          "sha1": "85a01164a2ceafb4ba1b9398bb99f4dd55e02499",
          "md5": "2bcb4827e1275152fda35b1224ef2955"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15.jar",
          "url": "spring-boot-starter-tomcat-2.7.15.jar",
          "size": 4798,
          "sha512": "1af27c4e07b55254d5764743a61801cf12bc37c4a129a402998c88c1f51a44c2c154e2038411cd998ab42e286e89465fcd49261a7bdddd16ef757827b4785d77",
          "sha256": "51c096873d554a84c7bde8bd2dba385e6c0b6d58aaf8a41ee6b4ff65435c0c65",
          "sha1": "85a01164a2ceafb4ba1b9398bb99f4dd55e02499",
          "md5": "2bcb4827e1275152fda35b1224ef2955"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15.jar",
          "url": "spring-boot-starter-tomcat-2.7.15.jar",
          "size": 4798,
          "sha512": "1af27c4e07b55254d5764743a61801cf12bc37c4a129a402998c88c1f51a44c2c154e2038411cd998ab42e286e89465fcd49261a7bdddd16ef757827b4785d77",
          "sha256": "51c096873d554a84c7bde8bd2dba385e6c0b6d58aaf8a41ee6b4ff65435c0c65",
          "sha1": "85a01164a2ceafb4ba1b9398bb99f4dd55e02499",
          "md5": "2bcb4827e1275152fda35b1224ef2955"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.7.15-javadoc.jar",
          "size": 4746,
          "sha512": "c151734525430616cac0b93a345a8b9429057ff3bc4df52ed5dfa6c1ebab735b8609b9ca89b7f6719760c3a44aa7f0e3f77b0cc44c4a07bb240c57d16da31c9a",
          "sha256": "9fda3dcc52b2627f9d09785bad0f9f06dd0ae8dc2648360b493ba023a9da3f0f",
          "sha1": "f7ceb8c107650096262194dd09054a0c43c9370a",
          "md5": "2fe20bba8ccf425e55ddadd671ab83c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.15-sources.jar",
          "url": "spring-boot-starter-tomcat-2.7.15-sources.jar",
          "size": 4745,
          "sha512": "4f24f29aa3e0e416284add1bd74c5f47c06bf62e63f94287185362ccd08468244db4cf0fa72bfd1fbc56668b0abe0736fea1cbd0d1ad609a5bdfa6c3cd0cdea7",
          "sha256": "cc1a508a591d7ccb8050e4483d76a7b1d245fce816efc0d42ff048ed98fdb0a9",
          "sha1": "7a952f5cf6c67b98451a684cfedc9a55a52cdf58",
          "md5": "78aba1009cfeaa4e1bd8d95d3d15992e"
        }
      ]
    }
  ]
}
