{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15.jar",
          "url": "spring-boot-starter-logging-2.7.15.jar",
          "size": 4762,
          "sha512": "56473691a4cc4386fbaa3a7b97ef4dcf085feddc205ae25cf7ccec5135420f3d756efee8e54332d0ae5cb7ae48e49f7e5f70153360b8a3d64e9dc1d19f3ab8b9",
          "sha256": "06a23e246550aec465ce3ccb5ade284c3298ed97169ad1a5376c3c943c5334fa",
          "sha1": "1f4bece73c6e002fd0c113de552a746ab603b9be",
          "md5": "3d7bfe0f52a093d4421099977868033b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15.jar",
          "url": "spring-boot-starter-logging-2.7.15.jar",
          "size": 4762,
          "sha512": "56473691a4cc4386fbaa3a7b97ef4dcf085feddc205ae25cf7ccec5135420f3d756efee8e54332d0ae5cb7ae48e49f7e5f70153360b8a3d64e9dc1d19f3ab8b9",
          "sha256": "06a23e246550aec465ce3ccb5ade284c3298ed97169ad1a5376c3c943c5334fa",
          "sha1": "1f4bece73c6e002fd0c113de552a746ab603b9be",
          "md5": "3d7bfe0f52a093d4421099977868033b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15.jar",
          "url": "spring-boot-starter-logging-2.7.15.jar",
          "size": 4762,
          "sha512": "56473691a4cc4386fbaa3a7b97ef4dcf085feddc205ae25cf7ccec5135420f3d756efee8e54332d0ae5cb7ae48e49f7e5f70153360b8a3d64e9dc1d19f3ab8b9",
          "sha256": "06a23e246550aec465ce3ccb5ade284c3298ed97169ad1a5376c3c943c5334fa",
          "sha1": "1f4bece73c6e002fd0c113de552a746ab603b9be",
          "md5": "3d7bfe0f52a093d4421099977868033b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15.jar",
          "url": "spring-boot-starter-logging-2.7.15.jar",
          "size": 4762,
          "sha512": "56473691a4cc4386fbaa3a7b97ef4dcf085feddc205ae25cf7ccec5135420f3d756efee8e54332d0ae5cb7ae48e49f7e5f70153360b8a3d64e9dc1d19f3ab8b9",
          "sha256": "06a23e246550aec465ce3ccb5ade284c3298ed97169ad1a5376c3c943c5334fa",
          "sha1": "1f4bece73c6e002fd0c113de552a746ab603b9be",
          "md5": "3d7bfe0f52a093d4421099977868033b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-logging-2.7.15-javadoc.jar",
          "size": 4748,
          "sha512": "0f8c249568e7b1fe610dce04bab01851d10537f774b951cb56840b7d3122e48c8e3b386fddfdf4b23ff1e16c064b79426cd05eb7e4661203ec915acc621465bb",
          "sha256": "3cb53a2228d6d8a8222aa65a2896b615b2c0d5cefb16c6fbd617ca0b06c5a7f0",
          "sha1": "37e723223c8c3462c28fdb480ac89fe65e5f12d7",
          "md5": "9cee2c7854740340055355f77c454675"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.7.15-sources.jar",
          "url": "spring-boot-starter-logging-2.7.15-sources.jar",
          "size": 4746,
          "sha512": "aa85b75e34d0dc3e7a310dc5172fcc16f9c47127bc38d4a51298684e65a4ac0b8401d0f8938d979f2f0d44bf875128ee6c5c902b2cd4df4fdb6128748b4733fc",
          "sha256": "75e11d261b4d26b4334494bc36fbdd3e7230eb97401275d795015cb11789620d",
          "sha1": "51f6070023ed4a60f8564cedfe17a99e703dc150",
          "md5": "a029b2977e6bd3e0c7e466d93f51a10a"
        }
      ]
    }
  ]
}
