{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "2.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15.jar",
          "url": "spring-boot-starter-json-2.7.15.jar",
          "size": 4749,
          "sha512": "4a6992624acbf4e0ae60ab396e13883929ea815c7cd4caf7a8d79f8c140b606586102943295873126e2349d1039515cfcd1e665a2638fa2db33b9955350001b2",
          "sha256": "5c7d9ebb5b6568b9df92ae444f967f5145bcb74fa3ae685ffa8286ede34cfa34",
          "sha1": "006d1bc45796a194b253ab98fbaf608e320bb16c",
          "md5": "9c3b92bcaf9d65cf76d3e5fe68c389ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.29"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15.jar",
          "url": "spring-boot-starter-json-2.7.15.jar",
          "size": 4749,
          "sha512": "4a6992624acbf4e0ae60ab396e13883929ea815c7cd4caf7a8d79f8c140b606586102943295873126e2349d1039515cfcd1e665a2638fa2db33b9955350001b2",
          "sha256": "5c7d9ebb5b6568b9df92ae444f967f5145bcb74fa3ae685ffa8286ede34cfa34",
          "sha1": "006d1bc45796a194b253ab98fbaf608e320bb16c",
          "md5": "9c3b92bcaf9d65cf76d3e5fe68c389ba"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15.jar",
          "url": "spring-boot-starter-json-2.7.15.jar",
          "size": 4749,
          "sha512": "4a6992624acbf4e0ae60ab396e13883929ea815c7cd4caf7a8d79f8c140b606586102943295873126e2349d1039515cfcd1e665a2638fa2db33b9955350001b2",
          "sha256": "5c7d9ebb5b6568b9df92ae444f967f5145bcb74fa3ae685ffa8286ede34cfa34",
          "sha1": "006d1bc45796a194b253ab98fbaf608e320bb16c",
          "md5": "9c3b92bcaf9d65cf76d3e5fe68c389ba"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15.jar",
          "url": "spring-boot-starter-json-2.7.15.jar",
          "size": 4749,
          "sha512": "4a6992624acbf4e0ae60ab396e13883929ea815c7cd4caf7a8d79f8c140b606586102943295873126e2349d1039515cfcd1e665a2638fa2db33b9955350001b2",
          "sha256": "5c7d9ebb5b6568b9df92ae444f967f5145bcb74fa3ae685ffa8286ede34cfa34",
          "sha1": "006d1bc45796a194b253ab98fbaf608e320bb16c",
          "md5": "9c3b92bcaf9d65cf76d3e5fe68c389ba"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.7.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15-javadoc.jar",
          "url": "spring-boot-starter-json-2.7.15-javadoc.jar",
          "size": 4746,
          "sha512": "3e2ae9404fc1f755d2ede9bbd68f60cc6d02caaf2e08b6c14e47598b09111f972f69aa65801ec34686dfabeed9f594486793ccc35a2c45815dea5be2684c68d9",
          "sha256": "5d0719220fc8b92eb2d567f2d0979075f7dddbf5cc7851a695f2203187b531e3",
          "sha1": "90173350b88ba8d8bbcacd9dfa643093a50dc046",
          "md5": "3569031bc2c012c61d35cb840c9f0e25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.7.15-sources.jar",
          "url": "spring-boot-starter-json-2.7.15-sources.jar",
          "size": 4744,
          "sha512": "2e51794a742852706fc7f792ab014c0063a7939f9e050e61e0ce0c4e5cd15fa97884898d3df1860845f41943643207eb8d122c44fc07142bd398dfbc24bc553d",
          "sha256": "3833dcf5543ad958e5b102084f9710ee3bfffc3aabe6e2149745090d881da656",
          "sha1": "9f2b5dcf67e0396fe9d72c5eff9ad7c0286156b5",
          "md5": "ecb5fb299847f0d1486834ada54052b2"
        }
      ]
    }
  ]
}
