name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Dev 브랜치로의 푸시 또는 PR인 경우 Jacoco 실행
      - name: Build with Gradle (Dev, with Jacoco)
        if: github.ref == 'refs/heads/dev' || github.head_ref == 'dev'
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build -PgenerateJacocoReport=true

      # Main 브랜치로의 푸시 또는 PR인 경우 Jacoco 보고서 생략
      - name: Build with Gradle (Main, without Jacoco)
        if: github.ref == 'refs/heads/main' || github.head_ref == 'main'
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build -PgenerateJacocoReport=false # default=false 이지만 명시적으로 넣음

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_ssh_key.pem
          chmod 600 ec2_ssh_key.pem
          scp -i ec2_ssh_key.pem -o StrictHostKeyChecking=accept-new ./build/libs/HaeChukGael.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/
          ssh -i ec2_ssh_key.pem -o StrictHostKeyChecking=accept-new ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart HaeChukGael.service"
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
      - name: Verify deployment
        run: |
          ssh -i ec2_ssh_key.pem -o StrictHostKeyChecking=accept-new ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "systemctl is-active HaeChukGael.service || exit 1"
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}